version: '3'
services:
  nacos:
    image: seataio/seata-server:1.6.1
    # 容器名称
    container_name: seata-server1.6.1
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=192.168.50.193 # 宿主机ip
    # 端口映射
    ports:
      - 8091:8091
      - 7091:7091
    volumes:
      - /home/sanshi/Desktop/myProject/docker_demo/seata/logs:/root/logs
      - /home/sanshi/Desktop/myProject/docker_demo/seata/config/application.yml:/seata-server/resources/application.yml