server:
  port: 8001
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://192.168.50.193/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: train_member
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: member

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.jiawa.train.member.mapper: trace
