version: '3'
services:
  nacos:
    image: bladex/sentinel-dashboard:1.8.6
    # 容器名称
    container_name: sentinel-dashboard1.8.6
    # environment:
      # - SEATA_PORT=8091
      # - SEATA_IP=192.168.50.193 # 宿主机ip
    # 端口映射
    ports:
      - 18080:8858
    volumes:
      - /home/sanshi/Desktop/myProject/docker_demo/sentinel/logs:/root/logs
      # - /home/sanshi/Desktop/myProject/docker_demo/seata/config/application.yml:/seata-server/resources/application.yml