version: '3'
services:
  nacos:
    image: nacos/nacos-server:v2.2.1
    # 容器名称
    container_name: nacos2.2.1
    # 端口映射
    ports:
      - 8848:8848
      - 9848:9848
    # 容器权限
    # privileged: true
    # 参数设置
    environment:
      # JVM_XMS: 128m
      # JVM_XMX: 128m
      # JVM_MS: 64m
      # JVM_MMS: 64m
      - MODE=standalone
      # - NACOS_AUTH_ENABLE=false
      # PREFER_HOST_MODE: ip
    volumes:
      - /home/sanshi/Desktop/myProject/docker_demo/nacos/logs:/home/nacos/logs
      - /home/sanshi/Desktop/myProject/docker_demo/nacos/data:/home/nacos/data
      - /home/sanshi/Desktop/myProject/docker_demo/nacos/config/application.properties:/home/nacos/conf/application.properties

