server:
  port: 8000


#路由转发，将/member/...的请求转发到member模块
spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: lb://member

        - id: business
          predicates:
            - Path=/business/**
          uri: lb://business

        - id: batch
          predicates:
            - Path=/batch/**
          uri: lb://batch
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOriginPatterns: "*"  # 允许所有的请求域名访问
#                allowedOrigins: "*"  # 允许所有的请求域名访问
                allowedMethods: # 允许所有的请求方法访问
                - GET
                - POST
                - PUT
                - DELETE
                allowedHeaders: "*" # 允许所有的请求头访问
                allowCredentials: true # 允许携带cookie跨域
                maxAge: 3600 # 预检请求的有效期，单位为秒。有效期内，不会重复发送预检请求

