server:
  port: 8002
  servlet:
    context-path: /business
spring:
  datasource:
    url: jdbc:mysql://192.168.50.193/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: train_business
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: business

  cloud:
    openfeign:
      client:
        config:
          business:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: full
            request-interceptors:
              - com.jiawa.train.common.interceptor.OkHttpReqInterceptor
            response-interceptor: com.jiawa.train.common.interceptor.OkHttpResqInterceptor
      okhttp:
        enabled: true
#      httpclient:
#        enabled: false
#        max-connections: 110 # 最大连接数
#        max-connections-per-route: 10 # 每个路由最大连接数
#        time-to-live: 60000 # 连接存活时间
#        time-to-live-unit: MILLISECONDS # 连接存活时间单位
#        connection-timeout: 5000 # 连接超时时间
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:18080
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cache:
    type: redis
    redis:
      key-prefix: train_cache_
      time-to-live: 60s
      cache-null-values: true
      use-key-prefix: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.jiawa.train.business.mapper: trace
