server:
  port: 8003
  servlet:
    context-path: /batch
spring:
  datasource:
    url: jdbc:mysql://192.168.50.193/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: train_business
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.jiawa.train.batch.mapper: trace
